spring:
  datasource:
    url: jdbc:mysql://localhost:3306/person?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
server:
  port: 8082
