server:
  port: 8081

addPerson:
  url: http://localhost:8082/person/insert

findPerson:
  url: http://localhost:8082/person/

updatePerson:
  url: http://localhost:8082/person/update/{id}

deletePerson:
  url: http://localhost:8082/person/delete/{id}
