server:
  port: 8082

addPerson:
  url: http://localhost:8088/person/insert

findPerson:
  url: http://localhost:8088/person/{id}

updatePerson:
  url: http://localhost:8088/person/update/{id}

deletePerson:
  url: http://localhost:8088/person/delete/{id}
